---
- name: Install required packages
  loop:
    - sanoid
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - sanoid

- name: Create config dir
  ansible.builtin.file:
    name: /etc/sanoid
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - sanoid

- name: Write config file
  notify:
    - Restart sanoid
  ansible.builtin.template:
    src: config.j2
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - sanoid

- name: Start sanoid service
  ansible.builtin.systemd:
    name: sanoid
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - sanoid

...
