---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
  env:
    ANSIBLE_GALAXY_DISPLAY_PROGRESS: "false"

driver:
  name: molecule_hetznercloud

platforms:
  - name: sanoid-ubuntu-24
    image: ubuntu-24.04
    server_type: cx23
    location: fsn1
  - name: sanoid-ubuntu-22
    image: ubuntu-22.04
    server_type: cx23
    location: fsn1

provisioner:
  name: ansible
  connection_options:
    ansible_become: true
  env:
    ANSIBLE_FILTER_PLUGINS: "${ANSIBLE_FILTER_PLUGINS:-./plugins/filter}"
    ANSIBLE_LIBRARY: "${ANSIBLE_LIBRARY:-./library}"

verifier:
  name: testinfra

...
