---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Stat apt dir
      register: aptdir
      ansible.builtin.stat:
        path: /var/lib/apt

    - name: Wait for aptlock
      when: aptdir.stat.exists
      changed_when: false
      ansible.builtin.shell:
        cmd: while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do echo 'Waiting for apt list lock.' && sleep 10; done

    - name: Update package cache
      when: aptdir.stat.exists
      ansible.builtin.apt:
        update_cache: true

    - name: Install test dependencies
      when: aptdir.stat.exists
      loop:
        - python3-gpg
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present

...
